---
version: "3.5"

volumes:
  exclude:

services:
  villain-spa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: villain-spa
    hostname: villain-spa
    environment:
      - GIT_REF_HASH=local
    ports:
      - 3000:3000
      - 80:3000
    volumes:
      - exclude:/villain/node_modules/:z
      - ./spa:/villain:z