name: deploy-main

on:
  push:
    branches: 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Build spa
        run: |
          cd spa
          npm install
          npm run build --if-present
      - name: Save build artifact
        uses: actions/upload-artifact@v3
        with:
          working-directory: ./spa
          name: build-folder
          path: build/
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-folder
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
      - name: Upload to S3
        run: |
          aws s3 sync build/ s3://villain.network/